name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '11'
       # check-path: 'src'
        exclude-regex: (no-format|some-format/hello.cpp)
        fallback-style: 'Google' # optional
