name: build using script

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

job:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: run a script
      run: ./scripts/build.sh
